// i18n.js -- the web reader's half of "a language is a data file".
//
// The catalogues under web/i18n/ are generated by tools/i18n/generate.py from
// the same i18n/strings/*.json the Android app reads. That is the whole reason
// this module exists in this shape: two hand-maintained catalogues would mean
// every language gets translated twice, and the two would drift the first time
// anyone was in a hurry -- which in practice means the web reader stays in
// English while the app moves on.
//
// FALLBACK IS PER KEY, deliberately, matching Android's own resource
// resolution. A locale that is 41% translated shows 41% in the reader's
// language and English for the rest. Never a blank, never a key name. Without
// that property the only honest options are "finish a language or don't offer
// it", which is how a project ends up shipping two.

const BASE = 'en';
const STORAGE_KEY = 'nooz.language';

// Scripts written right to left. Kept here rather than derived, because the
// answer belongs to the script and there is no reliable way to ask the browser.
const RTL = new Set(['ar', 'fa', 'ur', 'ks', 'he', 'ps', 'sd', 'yi']);

let base = {};        // the English catalogue: the floor every lookup lands on
let active = {};      // the chosen locale's catalogue, possibly partial
let activeTag = BASE;
let index = { total: 0, locales: [] };  // what can be offered, and how complete
const listeners = new Set();

/**
 * The locales worth offering, with their own names for themselves and how much
 * of the interface each carries. Generated into web/i18n/index.json from
 * Locales.kt and the catalogues, so this list and the Android picker's cannot
 * disagree.
 */
export function availableLocales() {
  return index.locales;
}

/** The reader's stored choice, or '' meaning "follow the browser". */
export function storedLanguage() {
  try {
    return localStorage.getItem(STORAGE_KEY) || '';
  } catch (_err) {
    // Private windows and blocked site data both throw here. Following the
    // browser is a perfectly good answer, so this is not worth an error.
    return '';
  }
}

/**
 * Which catalogue to load, given a stored choice and what the browser reports.
 *
 * `navigator.languages` is ordered by preference and often carries regional
 * tags (`pt-BR`, `zh-Hans-CN`) that no catalogue is named after, so each is
 * tried whole and then progressively shortened. Exported for the tests: this is
 * the part with actual logic in it.
 */
export function resolveTag(stored, preferred, available) {
  const have = new Set(available);
  const candidates = stored ? [stored] : (preferred || []);
  for (const raw of candidates) {
    const tag = String(raw || '').trim();
    if (!tag) continue;
    if (have.has(tag)) return tag;
    // Case-insensitive: browsers send `zh-hans`, catalogues are `zh-Hans`.
    const ci = [...have].find((t) => t.toLowerCase() === tag.toLowerCase());
    if (ci) return ci;
    // `pt-BR` -> `pt`, `zh-Hans-CN` -> `zh-Hans` -> `zh`.
    const parts = tag.split('-');
    for (let i = parts.length - 1; i > 0; i--) {
      const shorter = parts.slice(0, i).join('-');
      const match = [...have].find((t) => t.toLowerCase() === shorter.toLowerCase());
      if (match) return match;
    }
  }
  return BASE;
}

export function direction(tag) {
  return RTL.has(String(tag).split('-')[0]) ? 'rtl' : 'ltr';
}

export function currentLanguage() {
  return activeTag;
}

/** How much of the interface this locale actually carries, 0–100. */
export function coverage(strings) {
  const total = Object.keys(base).length;
  if (!total) return 0;
  return Math.round((Object.keys(strings || active).length / total) * 100);
}

async function fetchCatalogue(tag) {
  const response = await fetch(`i18n/${encodeURIComponent(tag)}.json`, { cache: 'no-cache' });
  if (!response.ok) throw new Error(`no catalogue for ${tag}`);
  return response.json();
}

/**
 * Load the base catalogue and the reader's locale.
 *
 * The base is loaded first and separately: if the chosen locale's file is
 * missing or malformed the reader gets an English interface, which is a
 * degraded experience but a working one. If the base itself cannot load, the
 * lookups below return their key's own fallback text rather than throwing --
 * a reader should never lose the app over a failed translation fetch.
 */
export async function init() {
  try {
    const response = await fetch('i18n/index.json', { cache: 'no-cache' });
    if (response.ok) index = await response.json();
  } catch (_err) {
    // No index means no picker and an English interface -- degraded, working.
  }
  try {
    base = await fetchCatalogue(BASE);
  } catch (_err) {
    base = {};
  }
  const available = index.locales.map((l) => l.tag);
  const tag = resolveTag(storedLanguage(), navigator.languages || [navigator.language], available);
  await applyTag(tag);
}

async function applyTag(tag) {
  if (tag === BASE) {
    active = base;
    activeTag = BASE;
  } else {
    try {
      active = await fetchCatalogue(tag);
      activeTag = tag;
    } catch (_err) {
      active = base;
      activeTag = BASE;
    }
  }
  // The two attributes that make a page legible to a screen reader in a
  // language other than the document's default: `lang` picks the voice and
  // pronunciation rules, `dir` decides which way the text runs. Getting `lang`
  // wrong makes a screen reader read Hindi with English phonetics.
  const html = document.documentElement;
  html.setAttribute('lang', activeTag);
  html.setAttribute('dir', direction(activeTag));
  for (const listener of listeners) listener(activeTag);
}

/** Switch language. '' means "follow the browser" again. */
export async function setLanguage(tag) {
  try {
    if (tag) localStorage.setItem(STORAGE_KEY, tag);
    else localStorage.removeItem(STORAGE_KEY);
  } catch (_err) {
    // The choice will not survive a reload, but it can still apply now.
  }
  const available = index.locales.map((l) => l.tag);
  await applyTag(resolveTag(tag, navigator.languages || [navigator.language], available));
}

export function onLanguageChange(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

/**
 * Look up a string.
 *
 * @param {string} key       a key from i18n/strings/en.json
 * @param {string} fallback  what to show if neither catalogue has loaded. Not
 *   optional by convention: a network failure must not put a key name like
 *   `tour_loom_body` in front of a reader.
 * @param {object} args      values for %1$s / %2$d placeholders, by position
 */
export function t(key, fallback, args) {
  const template = (key in active ? active[key] : base[key]) ?? fallback ?? '';
  return args && args.length ? format(template, args) : template;
}

/**
 * Fill Android-style positional placeholders: %1$s, %2$d, and %% for a literal
 * percent sign. Positional rather than sequential because that is what lets a
 * translation reorder the arguments, which several of these languages need.
 */
export function format(template, args) {
  return String(template).replace(/%(\d+)\$[sd]|%%/g, (match, index) => {
    if (match === '%%') return '%';
    const value = args[Number(index) - 1];
    return value === undefined || value === null ? '' : String(value);
  });
}

/** Numbers in the reader's own digits and grouping. */
export function formatNumber(value) {
  try {
    return new Intl.NumberFormat(activeTag).format(value);
  } catch (_err) {
    return String(value);
  }
}
