package xyz.mdhv.riverwip

import android.app.LocaleManager
import android.content.Context
import android.content.ContextWrapper
import android.os.Build
import android.os.LocaleList
import java.util.Locale as JavaLocale

/**
 * Which language Nooz shows *itself* in.
 *
 * Two paths, because per-app language became a platform feature in the middle
 * of this app's supported range (minSdk 31):
 *
 *  - **API 33+**: `LocaleManager`. The system owns the choice, which is the
 *    point — it survives reinstalls, and the same setting appears in Android's
 *    own Settings › Apps › Nooz › Language, so a reader who looks for it where
 *    every other app keeps it will find it. `locales_config.xml` (generated by
 *    tools/i18n/generate.py) is what puts Nooz in that list at all.
 *  - **API 31–32**: no platform support, so the choice is mirrored in
 *    SharedPreferences and applied in `attachBaseContext`. SharedPreferences
 *    rather than the DataStore that holds every other setting, for one reason:
 *    `attachBaseContext` runs before anything can suspend, and it needs the
 *    answer synchronously. It is a mirror, not a second source of truth.
 *
 * Deliberately **not** AppCompat. `AppCompatDelegate.setApplicationLocales`
 * would cover both paths, but it needs an AppCompat-based activity and theme,
 * and this app is Compose over the platform themes on purpose (D34's
 * per-configuration parents). Pulling in a whole compat theme layer for two API
 * levels is a worse trade than twenty lines.
 */
object AppLocale {

    private const val PREFS = "nooz_locale"
    private const val KEY_TAG = "language_tag"

    /** The empty tag means "follow the phone", which is the default. */
    const val SYSTEM_DEFAULT = ""

    /** The tag currently in force, or [SYSTEM_DEFAULT]. */
    fun current(context: Context): String =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            context.getSystemService(LocaleManager::class.java)
                ?.applicationLocales
                ?.takeIf { !it.isEmpty }
                ?.get(0)
                ?.toLanguageTag()
                ?: SYSTEM_DEFAULT
        } else {
            context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getString(KEY_TAG, SYSTEM_DEFAULT) ?: SYSTEM_DEFAULT
        }

    /**
     * Switch the interface language.
     *
     * @return true if the caller must recreate the activity itself. On API 33+
     *   the platform does it; below that it is ours to do.
     */
    fun set(context: Context, tag: String): Boolean {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            context.getSystemService(LocaleManager::class.java)?.applicationLocales =
                if (tag == SYSTEM_DEFAULT) LocaleList.getEmptyLocaleList()
                else LocaleList.forLanguageTags(tag)
            return false
        }
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putString(KEY_TAG, tag)
            .apply()
        return true
    }

    /**
     * Wrap a base context in the chosen locale. Called from
     * `Activity.attachBaseContext`; a no-op on API 33+, where the platform has
     * already applied the choice before the activity is built.
     */
    fun wrap(base: Context): Context {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) return base
        val tag = current(base)
        if (tag == SYSTEM_DEFAULT) return base
        val locale = JavaLocale.forLanguageTag(tag)
        val config = android.content.res.Configuration(base.resources.configuration)
        config.setLocales(LocaleList(locale))
        // setLayoutDirection is what makes Urdu and Kashmiri lay out
        // right-to-left below API 33; the platform does it for us above.
        config.setLayoutDirection(locale)
        return ContextWrapper(base.createConfigurationContext(config))
    }
}
